config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get '/signup',   to: 'users#new'
  get '/login',    to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  # 拠点情報
  resources :bases
  # 出勤中社員
  get '/workers', to: 'attendances#index'
  # 基本情報更新 未使用
  get '/edit_basic_info/:id', to: 'users#edit_basic_info', as: :basic_info
  patch 'update_basic_info', to: 'users#update_basic_info'
  # 勤怠編集更新
  get 'users/:id/attendances/:date/edit', to: 'attendances#edit', as: :edit_attendances
  patch 'users/:id/attendances/:date/update', to: 'attendances#update', as: :update_attendances
  # 残業申請更新
  get 'users/:id/attendances/:date/edit_overtime', to: 'attendances#edit_overtime', as: :edit_attendances_overtime
  patch 'users/:id/attendances/:date/update_overtime', to: 'attendances#update_overtime', as: :update_attendances_overtime
  # 各種お知らせ
  get 'users/:id/attendances/:date/edit_superior_notice', to: 'attendances#edit_superior_notice', as: :edit_superior_notice
  patch 'users/:id/attendances/:date/update_superior_notice', to: 'attendances#update_superior_notice', as: :update_superior_notice
  get 'users/:id/attendances/:date/edit_attendance_notice', to: 'attendances#edit_attendance_notice', as: :edit_attendance_notice
  patch 'users/:id/attendances/:date/update_attendance_notice', to: 'attendances#update_attendance_notice', as: :update_attendance_notice
  get 'users/:id/attendances/:date/edit_overtime_notice', to: 'attendances#edit_overtime_notice', as: :edit_overtime_notice
  patch 'users/:id/attendances/:date/update_overtime_notice', to: 'attendances#update_overtime_notice', as: :update_overtime_notice
  # １ヶ月分の勤怠申請
  patch 'users/:id/attendances/:date/update_one_month', to: 'attendances#update_one_month', as: :update_one_month
  # 勤怠ログ
  get 'users/:id/attendances/:date/time_log', to: 'attendances#time_log', as: :time_log
  get 'ajax', to: 'attendances#ajax', as: :ajax
  
  resources :users do
    get :show_confirmation, on: :member
    collection { post :import }
    resources :attendances, only: :create
  end
end

app/models/user.rb
class User < ApplicationRecord

  has_many :attendances, dependent: :destroy    
  before_save {self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: {case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  validates :affiliation, length: { in: 3..50 }, allow_blank: true
  
  # csvインポート
  def self.import(file)
    CSV.foreach(file.path, headers: true, encoding: 'Shift_JIS:UTF-8') do |row|
      user = find_by(id: row["id"]) || new
      user.attributes = row.to_hash.slice(*updatable_attributes)
      user.save
    end
  end
  # csvインポート更新を許可するカラムを定義
  def self.updatable_attributes
    ["name", "email", "affiliation", "employee_number", "uid", "basic_work_time", "designated_work_start_time", "designated_work_end_time", "superior", "admin", "password"]
  end
  
  # 所属長承認申請モーダルのお知らせのeach
  def self.application_manager_approval(superior: user)
    joins(:attendances).where.not(attendances: {superior_selector: nil, user_id: superior.id, superior_mark: 3}).distinct
  end
  
  # 勤怠変更モーダルのお知らせのeach
  def self.attendance_change(superior: user)
    joins(:attendances).where.not(attendances: {started_at_2: nil, finished_at_2: nil, user_id: superior.id, attendance_mark: 3}).distinct
  end
  
  # 残業申請モーダルのお知らせのeach
  def self.overtime_applied_users(superior: user)
    joins(:attendances).where.not(attendances: {expected_end_time: nil, user_id: superior.id, overtime_mark: 3}).distinct
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :show, :edit, :update, :destroy]
  before_action :correct_user,   only: [:show]
  before_action :correct_user_or_admin_user,   only: [:show]
  before_action :admin_user,     only: [:index, :destroy, :edit_basic_info, :update_basic_info]
  
  def index
    @users = User.paginate(page: params[:page])
  end
  
  def import
    # ファイルセットされていたら保存と結果のメッセージを取得して表示
    if !params[:file].blank?
      # 保存と結果のメッセージを取得して表示
      User.import(params[:file])
      flash[:notice] = "CSVファイルをインポートしました。"
    else
      flash[:error] = "読み込むCSVファイルをセットしてください"
    end
    redirect_to users_path
  end
  
  def show
    @user = User.find(params[:id])
    @first_day = first_day(params[:first_day])
    @last_day = @first_day.end_of_month
    (@first_day..@last_day).each do |day|
      unless @user.attendances.any? {|attendance| attendance.worked_on == day}
        record = @user.attendances.build(worked_on: day)
        record.save
      end
    end
    @dates = user_attendances_month_date
    @worked_sum = @dates.where.not(started_at: nil).count
    respond_to do |format|
      format.html
      format.csv do
        send_data render_to_string, filename: "勤怠情報.csv", type: :csv
      end
    end
    @su_count = Attendance.where(superior_selector: @user.id).where.not(superior_selector: nil, superior_mark: 3).count
    @at_count = Attendance.where(superior_selection: @user.id).where.not(started_at_2: nil, attendance_mark: 3).count
    @count = Attendance.where(superior_select: @user.id).where.not(expected_end_time: nil, overtime_mark: 3).count
    @users = User.where(superior: true).where.not(id: @user.id)
    @attendance = Attendance.find(params[:id])
  end
  
  def show_confirmation
    @user = User.find(params[:id])
    @first_day = first_day(params[:first_day])
    @last_day = @first_day.end_of_month
    (@first_day..@last_day).each do |day|
      unless @user.attendances.any? {|attendance| attendance.worked_on == day}
        record = @user.attendances.build(worked_on: day)
        record.save
      end
    end
    @dates = user_attendances_month_date
    @worked_sum = @dates.where.not(started_at: nil).count
    @users = User.where(superior: true).where.not(id: @user.id)
    @attendance = Attendance.find(params[:id])
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "ユーザーの新規登録に成功しました。"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "ユーザー情報を更新しました。"
      if params[:commit] == "更新"
        redirect_to users_url
      else
        redirect_to edit_user_url
      end
    else
      render :edit
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "削除しました。"
    redirect_to users_url
  end
  # 未使用
  def edit_basic_info
    @user = User.find(params[:id])
  end
  # 未使用
  def update_basic_info
    @user = User.find(params[:id])
    if @user.update_attributes(basic_info_params)
      flash[:success] = "基本情報を更新しました。"
      redirect_to @user
    else
      render 'edit_basic_info' 
    end
  end
  
  private
  
    def user_params
      params.require(:user).permit(:name, :email, :affiliation, :employee_number,
                                   :uid, :basic_work_time, :designated_work_start_time,
                                   :designated_work_end_time, :password, :password_confirmation)
    end
    
    def basic_info_params
      params.require(:user).permit(:basic_time, :work_time)
    end
    
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "ログインしてください。"
        redirect_to login_url
      end
    end
    
end

app/helpers/users_helper.rb
module UsersHelper
  
  def format_basic_time(datetime)
    format("%.2f", ((datetime.hour * 60) + datetime.min)/60.0)
  end
  
  def format_over_time(datetime)
    format("%.2f", ((datetime.hour * 60) + datetime.min)/60.0 + 24.0)
  end
end

app/views/users/edit.html.erb
<% provide(:title, 'アカウント編集') %>
<% provide(:button_text, '更新する') %>

<h1>アカウント情報の更新</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/edit_basic_info.html.erb
<% provide(:title, "基本情報編集") %>

<!--<h1>基本情報の編集</h1>-->

<!--<div class="row">-->
<!--  <div class="col-md-6 col-md-offset-3">-->
<!--    <%#= form_for(@user, url: update_basic_info_path(params: {id: @user.id})) do |f| %>-->
<!--      <%#= render 'shared/error_messages', object: @user %>-->
      
<!--      <%#= f.label "basic_time" %>-->
<!--      <%#= f.time_field :basic_time, class: "form-control" %>-->
      
<!--      <%#= f.label "work_time" %>-->
<!--      <%#= f.time_field :work_time, class: "form-control" %>-->
      
<!--      <%#= f.submit "更新する", class: "btn btn-primary" %>-->
<!--    <%# end %>-->
<!--  </div>-->
<!--</div>-->

app/views/users/new.html.erb
<% provide(:title, '新規作成') %>
<% provide(:button_text, '作成する') %>
<h1>ユーザー作成</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, '勤怠情報') %>
<div>
  <div>
    <table class="table-bordered table-condensed">
      <tbody>
        <tr>
          <td colspan="2">
            <%= link_to "←", user_path(params: {id: @user.id, first_day: @first_day.prev_month}),
                             class: "btn btn-xs btn-primary" %>
            &emsp;<%= @first_day.to_s(:year_month) %> 時間管理表&emsp;
            <%= link_to "→", user_path(params: {id: @user.id, first_day: @first_day.next_month}),
                             class: "btn btn-xs btn-primary" %>
          </td>
          <td colspan="1">指定勤務開始時間:<%= format_basic_time(@user.designated_work_start_time) %><br>
                          指定勤務終了時間:<%= format_basic_time(@user.designated_work_end_time) %></td>
          <td colspan="2">基本時間:<%= format_basic_time(@user.basic_work_time) %></td>
          <td colspan="1">初日 <%= @first_day.to_s(:date) %></td>
        </tr>
        <tr>
          <td colspan="2">所属:<%= @user.affiliation.present? ? @user.affiliation : "未設定" %></td>
          <td colspan="1">名前:<%= @user.name %></td>
          <td colspan="1">コード:<%= @user.id %></td>
          <td colspan="1">出勤日数:<%= @worked_sum %>日</td>
          <td colspan="1">締日 <%= @last_day.to_s(:date) %></td>
        </tr>
      </tbody>
    </table>
  </div>
  <% @dates.each do |day| %>
    <div class="btn-i">
      <% if current_user.superior? && @su_count && @su_count != 0 %>
        <%= link_to "【所属長承認申請のお知らせ】#{@su_count}件のお知らせがあります。", edit_superior_notice_path(@user, day.worked_on), remote: true, :style=>"color:red;" %>
      <% elsif current_user.superior? %>
        <%= "【所属長承認申請のお知らせ】" %>
      <% end %>
    </div>
    <div class="btn-i">
      <% if current_user.superior? && @at_count && @at_count != 0 %>
        <%= link_to "【勤怠変更申請のお知らせ】#{@at_count}件のお知らせがあります。", edit_attendance_notice_path(@user, day.worked_on), remote: true, :style=>"color:red;" %>
      <% elsif current_user.superior? %>
        <%= "【勤怠変更申請のお知らせ】" %>
      <% end %>  
    </div>
    <div class="btn-i">
      <% if current_user.superior? && @count && @count != 0 %>
        <%= link_to "【残業申請のお知らせ】#{@count}件のお知らせがあります。", edit_overtime_notice_path(@user, day.worked_on), remote: true, :style=>"color:red;" %>
      <% elsif current_user.superior? %>
        <%= "【残業申請のお知らせ】" %>
      <% end %>
    </div>
  <% break %>
  <% end %>
  
  <div class="btn-b">
    <%= link_to "勤怠編集", edit_attendances_path(@user, @first_day), class: "btn btn-primary" %>&emsp;
    <%= link_to "CSV出力", user_path(@user, first_day: @first_day, format: :csv), class: "btn btn-primary" %>&emsp;
    <%= link_to "勤怠修正ログ(承認済)", time_log_path(@user, @first_day), class: "btn btn-primary" %>
  </div>
  
  <table class="table-bordered table-striped table-condensed">
    <thead>
      <tr>
        <th rowspan="3">残業申請</th>
        <th rowspan="3">日付</th>
        <th rowspan="3">曜日</th>
        <th colspan="8">[実績]</th>
        <th colspan="5">[所定外勤務]</th>
      </tr>
      <tr>
        <th colspan="3">出社</th>
        <th colspan="3">退社</th>
        <th rowspan="2">在社時間</th>
        <th rowspan="2">備考</th>
        <th colspan="2">終了予定時間</th>
        <th rowspan="2">時間外勤務</th>
        <th rowspan="2">業務処理内容</th>
        <th rowspan="2">指示者確認㊞</th>
      </tr>
      <tr>
        <th>時</th>
        <th>分</th>
        <th></th>
        <th>時</th>
        <th>分</th>
        <th></th>
        <th>時</th>
        <th>分</th>
      </tr>
    </thead>
    
    <tbody>
      <% @dates.each do |day| %>
        <tr>
          <td><%= link_to "残業申請", edit_attendances_overtime_path(@user, day.worked_on), remote: true, class: "btn btn-primary" %></td>
          <td><%= day.worked_on.to_s(:date) %></td>
          <td>
            <% if day.worked_on.wday == 0 %>
              <font color="red">日</font>
            <% elsif day.worked_on.wday == 6 %>
              <font color="blue">土</font>
            <% else %>
              <%= %w{日 月 火 水 木 金 土}[day.worked_on.wday] %>
            <% end %>
          </td>
          <td>
            <% if day.started_at_2.present? %>
              <%= day.started_at_2.to_s(:hour) %>
            <% elsif day.started_at.present? %>
              <%= day.started_at.to_s(:hour) %>
            <% end %>
          </td>
          <td>
            <% if day.started_at_2.present? %>
              <%= day.started_at_2.time.to_s(:min) %>
            <% elsif day.started_at.present? %>
              <%= day.started_at.to_s(:min) %>
            <% end %>
          </td>
          <td>
            <% if day.worked_on == Date.today && day.started_at.nil? %>
              <%= button_to "出社", user_attendances_path(@user), class: "btn btn-xs btn-primary" %>
            <% end %>
          </td>
          <td>
            <% if day.finished_at_2.present? %>
              <%= day.finished_at_2.to_s(:hour) %>
            <% elsif day.finished_at.present? %>
              <%= day.finished_at.to_s(:hour) %>
            <% end %>
          </td>
          <td>
            <% if day.finished_at_2.present? %>
              <%= day.finished_at_2.to_s(:min) %>
            <% elsif day.finished_at.present? %>
              <%= day.finished_at.to_s(:min) %>
            <% end %>
          </td>
          <td>
            <% if day.worked_on == Date.today && day.started_at.present? && day.finished_at.nil? %>
              <%= button_to "退社", user_attendances_path(@user), class: "btn btn-xs btn-primary" %>
            <% end %>
          </td>
          <td>
            <% if day.started_at_2.present? && day.finished_at_2.present? && day.attendance_next == true %>
              <%= working_times_attendance(day.started_at_2, day.finished_at_2) %> 
              <% seconds = (day.finished_at_2 - day.started_at_2) %>
              <% @total_seconds = @total_seconds.to_i + seconds %>
            <% elsif day.started_at_2.present? && day.finished_at_2.present? %>
              <%= working_times_2(day.started_at_2, day.finished_at_2) %> 
              <% seconds = (day.finished_at_2 - day.started_at_2) %>
              <% @total_seconds = @total_seconds.to_i + seconds %>
            <% elsif day.started_at.present? && day.finished_at.present? %>
              <%= working_times(day.started_at, day.finished_at) %> 
              <% seconds = (day.finished_at - day.started_at) %>
              <% @total_seconds = @total_seconds.to_i + seconds %>
            <% end %>
          </td>
          <td><%= day.note %></td>
          <!-- 残業申請 -->
          <td><%= day.expected_end_time.to_s(:hour) if day.expected_end_time.present? %></td>
          <td><%= day.expected_end_time.to_s(:min) if day.expected_end_time.present? %></td>
          <td>
            <% if day.next == true %>
              <%= format_over_time(day.expected_end_time).to_f - format_basic_time(@user.designated_work_end_time).to_f %>
            <% elsif day.expected_end_time.present? %>
              <%= format_basic_time(day.expected_end_time).to_f - format_basic_time(@user.designated_work_end_time).to_f %>
            <% end %>
          </td>
          <td><%= day.overtime_work %></td>
          <td>
            <% @users.each do |user| %>
              <% if day.overtime_mark == 3 && day.overtime_change == true && day.superior_select == user.id %>
                <%= "#{user.name}から残業【承認】" %><br>
              <% elsif day.overtime_mark == 4 && day.overtime_change == true && day.superior_select == user.id %>
                <%= "#{user.name}から残業【否認】" %><br>
              <% elsif day.superior_select == user.id %>
                <%= "#{user.name}へ残業【申請中】" %><br>
              <% end %>
              <% if day.attendance_mark == 3 && day.attendance_change == true && day.superior_selection == user.id %>
                <%= "#{user.name}から勤怠変更【承認】" %>
              <% elsif day.attendance_mark == 4 && day.attendance_change == true && day.superior_selection == user.id %>
                <%= "#{user.name}から勤怠変更【否認】" %>
              <% elsif day.superior_selection == user.id %>
                <%= "#{user.name}へ勤怠変更【申請中】" %>
              <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
    
    <tfoot>
      <tr>
        <td colspan="2"><%= format_basic_time(@user.basic_time).to_f * @worked_sum %></td>
        <td colspan="7"></td>
        <td><%= working_times_sum(@total_seconds) unless @total_seconds.nil? %></td>
        <td colspan="5"></td>
        <%= form_with(url: update_one_month_path(@user,@first_day), local: :true, method: :patch) do |f| %>
          <td>
            <% @dates.each do |day| %>
              <% @users.each do |user| %>
                <% if day.superior_mark == 3 && day.superior_change == true && day.superior_selector == user.id %>
                  <%= "所属長承認 #{user.name}から承認済"%>
                <% elsif day.superior_mark == 4 && day.superior_change == true && day.superior_selector == user.id %>
                  <%= "所属長承認 #{user.name}から否認"%>
                <% elsif day.superior_selector == user.id %>
                  <%= "所属長承認 #{user.name}へ申請中"%>
                <% end %>
              <% end %>
            <% end %>
            <%= f.collection_select :superior_selector, User.where(superior: true).where.not(id: @user.id), :id,:name %>
            <%= f.submit "所属長承認申請", class: "btn btn-md btn-primary", :style => "width:100%;"  %>
          </td>
        <% end %>
      </tr>
    </tfoot>
  </table>
</div>

<!--残業申請モーダルウインドウ表示-->
<div id="edit-overtime" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<!--所属長承認申請のお知らせモーダルウインドウ表示-->
<div id="edit-superior-notice" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<!--勤怠変更申請のお知らせモーダルウインドウ表示-->
<div id="edit-attendance-notice" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<!--残業申請のお知らせモーダルウインドウ表示-->
<div id="edit-overtime-notice" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

app/views/users/show_confirmation.html.erb
<% provide(:title, '勤怠確認') %>

<div>
  <div>
    <table class="table-bordered table-condensed">
      <tbody>
        <tr>
          <td colspan="2">
            <%= link_to "←", user_path(params: {id: @user.id, first_day: @first_day.prev_month}),
                             class: "btn btn-xs btn-primary", style: "display: none;" %>
            &emsp;<%= @first_day.to_s(:year_month) %> 時間管理表&emsp;
            <%= link_to "→", user_path(params: {id: @user.id, first_day: @first_day.next_month}),
                             class: "btn btn-xs btn-primary", style: "display: none;" %>
          </td>
          <td colspan="1">指定勤務開始時間:<%= format_basic_time(@user.designated_work_start_time) %><br>
                          指定勤務終了時間:<%= format_basic_time(@user.designated_work_end_time) %></td>
          <td colspan="2">基本時間:<%= format_basic_time(@user.basic_work_time) %></td>
          <td colspan="1">初日 <%= @first_day.to_s(:date) %></td>
        </tr>
        <tr>
          <td colspan="2">所属:<%= @user.affiliation.present? ? @user.affiliation : "未設定" %></td>
          <td colspan="1">名前:<%= @user.name %></td>
          <td colspan="1">コード:<%= @user.id %></td>
          <td colspan="1">出勤日数:<%= @worked_sum %>日</td>
          <td colspan="1">締日 <%= @last_day.to_s(:date) %></td>
        </tr>
      </tbody>
    </table>
  </div>
  <br>
  <br>
  <br>
  
  <table class="table-bordered table-striped table-condensed">
    <thead>
      <tr>
        <th rowspan="3">残業申請</th>
        <th rowspan="3">日付</th>
        <th rowspan="3">曜日</th>
        <th colspan="8">[実績]</th>
        <th colspan="5">[所定外勤務]</th>
      </tr>
      <tr>
        <th colspan="3">出社</th>
        <th colspan="3">退社</th>
        <th rowspan="2">在社時間</th>
        <th rowspan="2">備考</th>
        <th colspan="2">終了予定時間</th>
        <th rowspan="2">時間外勤務</th>
        <th rowspan="2">業務処理内容</th>
        <th rowspan="2">指示者確認㊞</th>
      </tr>
      <tr>
        <th>時</th>
        <th>分</th>
        <th></th>
        <th>時</th>
        <th>分</th>
        <th></th>
        <th>時</th>
        <th>分</th>
      </tr>
    </thead>
    
    <tbody>
      <% @dates.each do |day| %>
        <tr>
          <td><%= link_to "残業申請", edit_attendances_overtime_path(@user, day.worked_on), remote: true, class: "btn btn-primary", style: "display: none;" %></td>
          <td><%= day.worked_on.to_s(:date) %></td>
          <td>
            <% if day.worked_on.wday == 0 %>
              <font color="red">日</font>
            <% elsif day.worked_on.wday == 6 %>
              <font color="blue">土</font>
            <% else %>
              <%= %w{日 月 火 水 木 金 土}[day.worked_on.wday] %>
            <% end %>
          </td>
          <td>
            <% if day.started_at_2.present? %>
              <%= day.started_at_2.to_s(:hour) %>
            <% elsif day.started_at.present? %>
              <%= day.started_at.to_s(:hour) %>
            <% end %>
          </td>
          <td>
            <% if day.started_at_2.present? %>
              <%= day.started_at_2.time.to_s(:min) %>
            <% elsif day.started_at.present? %>
              <%= day.started_at.to_s(:min) %>
            <% end %>
          </td>
          <td>
            <% if day.worked_on == Date.today && day.started_at.nil? %>
              <%= button_to "出社", user_attendances_path(@user), class: "btn btn-xs btn-primary", style: "display: none;" %>
            <% end %>
          </td>
          <td>
            <% if day.finished_at_2.present? %>
              <%= day.finished_at_2.to_s(:hour) %>
            <% elsif day.finished_at.present? %>
              <%= day.finished_at.to_s(:hour) %>
            <% end %>
          </td>
          <td>
            <% if day.finished_at_2.present? %>
              <%= day.finished_at_2.to_s(:min) %>
            <% elsif day.finished_at.present? %>
              <%= day.finished_at.to_s(:min) %>
            <% end %>
          </td>
          <td>
            <% if day.worked_on == Date.today && day.started_at.present? && day.finished_at.nil? %>
              <%= button_to "退社", user_attendances_path(@user), class: "btn btn-xs btn-primary", style: "display: none;" %>
            <% end %>
          </td>
          <td>
            <% if day.started_at_2.present? && day.finished_at_2.present? && day.attendance_next == true %>
              <%= working_times_attendance(day.started_at_2, day.finished_at_2) %> 
              <% seconds = (day.finished_at_2 - day.started_at_2) %>
              <% @total_seconds = @total_seconds.to_i + seconds %>
            <% elsif day.started_at_2.present? && day.finished_at_2.present? %>
              <%= working_times_2(day.started_at_2, day.finished_at_2) %> 
              <% seconds = (day.finished_at_2 - day.started_at_2) %>
              <% @total_seconds = @total_seconds.to_i + seconds %>
            <% elsif day.started_at.present? && day.finished_at.present? %>
              <%= working_times(day.started_at, day.finished_at) %> 
              <% seconds = (day.finished_at - day.started_at) %>
              <% @total_seconds = @total_seconds.to_i + seconds %>
            <% end %>
          </td>
          <td><%= day.note %></td>
          <!-- 残業申請 -->
          <td><%= day.expected_end_time.to_s(:hour) if day.expected_end_time.present? %></td>
          <td><%= day.expected_end_time.to_s(:min) if day.expected_end_time.present? %></td>
          <td>
            <% if day.next == true %>
              <%= format_over_time(day.expected_end_time).to_f - format_basic_time(@user.designated_work_end_time).to_f %>
            <% elsif day.expected_end_time.present? %>
              <%= format_basic_time(day.expected_end_time).to_f - format_basic_time(@user.designated_work_end_time).to_f %>
            <% end %>
          </td>
          <td><%= day.overtime_work %></td>
          <td>
            <% @users.each do |user| %>
              <% if day.overtime_mark == 3 && day.overtime_change == true && day.superior_select == user.id %>
                <%= "#{user.name}から残業【承認】"%><br>
              <% elsif day.overtime_mark == 4 && day.overtime_change == true && day.superior_select == user.id %>
                <%= "#{user.name}から残業【否認】"%><br>
              <% elsif day.superior_select == user.id %>
                <%= "#{user.name}へ残業【申請中】"%><br>
              <% end %>
              <% if day.attendance_mark == 3 && day.attendance_change == true && day.superior_selection == user.id %>
                <%= "#{user.name}から勤怠変更【承認】"%>
              <% elsif day.attendance_mark == 4 && day.attendance_change == true && day.superior_selection == user.id %>
                <%= "#{user.name}から勤怠変更【否認】"%>
              <% elsif day.superior_selection == user.id %>
                <%= "#{user.name}へ勤怠変更【申請中】"%>
              <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
    
    <tfoot>
      <tr>
        <td colspan="2"><%= format_basic_time(@user.basic_time).to_f * @worked_sum %></td>
        <td colspan="7"></td>
        <td><%= working_times_sum(@total_seconds) unless @total_seconds.nil? %></td>
        <td colspan="5"></td>
        <td>
          <% @dates.each do |day| %>
            <% @users.each do |user| %>
              <% if day.superior_mark == 3 && day.superior_change == true && day.superior_selector == user.id %>
                <%= "所属長承認 #{user.name}から承認済"%>
              <% elsif day.superior_mark == 4 && day.superior_change == true && day.superior_selector == user.id %>
                <%= "所属長承認 #{user.name}から否認"%>
              <% elsif day.superior_selector == user.id %>
                <%= "所属長承認 未"%>
              <% end %>
            <% end %>
          <% end %>
        </td>
      </tr>
    </tfoot>
  </table>
</div>