config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get '/signup',   to: 'users#new'
  get '/login',    to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  # 拠点情報
  resources :bases
  # 出勤中社員
  get '/workers', to: 'attendances#index'
  # 基本情報更新 未使用
  get '/edit_basic_info/:id', to: 'users#edit_basic_info', as: :basic_info
  patch 'update_basic_info', to: 'users#update_basic_info'
  # 勤怠編集更新
  get 'users/:id/attendances/:date/edit', to: 'attendances#edit', as: :edit_attendances
  patch 'users/:id/attendances/:date/update', to: 'attendances#update', as: :update_attendances
  # 残業申請更新
  get 'users/:id/attendances/:date/edit_overtime', to: 'attendances#edit_overtime', as: :edit_attendances_overtime
  patch 'users/:id/attendances/:date/update_overtime', to: 'attendances#update_overtime', as: :update_attendances_overtime
  # 各種お知らせ
  get 'users/:id/attendances/:date/edit_superior_notice', to: 'attendances#edit_superior_notice', as: :edit_superior_notice
  patch 'users/:id/attendances/:date/update_superior_notice', to: 'attendances#update_superior_notice', as: :update_superior_notice
  get 'users/:id/attendances/:date/edit_attendance_notice', to: 'attendances#edit_attendance_notice', as: :edit_attendance_notice
  patch 'users/:id/attendances/:date/update_attendance_notice', to: 'attendances#update_attendance_notice', as: :update_attendance_notice
  get 'users/:id/attendances/:date/edit_overtime_notice', to: 'attendances#edit_overtime_notice', as: :edit_overtime_notice
  patch 'users/:id/attendances/:date/update_overtime_notice', to: 'attendances#update_overtime_notice', as: :update_overtime_notice
  # １ヶ月分の勤怠申請
  patch 'users/:id/attendances/:date/update_one_month', to: 'attendances#update_one_month', as: :update_one_month
  # 勤怠ログ
  get 'users/:id/attendances/:date/time_log', to: 'attendances#time_log', as: :time_log
  get 'ajax', to: 'attendances#ajax', as: :ajax
  
  resources :users do
    get :show_confirmation, on: :member
    collection { post :import }
    resources :attendances, only: :create
  end
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  validates :worked_on, presence: true
  validate :must_choice_superior, on: :update
  # 勤怠編集にて指示者を確認しなければいけない。
  def must_choice_superior
    if started_at_2.present? && finished_at_2.present? && started_at_2 < finished_at_2 && superior_selection.nil?
      errors.add(:superior_selection, "を選択して下さい。")
    end
  end
  
  # 当時の日付を持ち、かつ出勤時間のみに値が存在する状態のユーザーを取得する。
  scope :worker, -> {
    where(attendances: {worked_on: Date.current, finished_at: nil}).
    where.not(attendances: {started_at: nil})
  }
  
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :admin_user, only: :index
  
  def index
    @workers = Attendance.worker
  end

  def create
    @user = User.find(params[:user_id])
    @attendance = @user.attendances.find_by(worked_on: Date.today)
    if @attendance.started_at.nil?
      @attendance.update_attributes(started_at: current_time)
      flash[:info] = 'おはようございます。'
    elsif @attendance.finished_at.nil?
      @attendance.update_attributes(finished_at: current_time)
      flash[:info] = "おつかれさまでした。"  
    else
      flash[:danger] = 'トラブルがあり、登録出来ませんでした。'
    end
    redirect_to @user
  end
  
  # 所属長承認申請
  def update_one_month
    @user = User.find(params[:id])
    @first_day = first_day(params[:first_day])
    @attendance = Attendance.find_by(worked_on: params[:date], user_id: @user.id)
    if @attendance.update(superior_selector: params[:superior_selector], superior_mark: 2)
      flash[:success] = "所属長承認を申請しました。"
      redirect_to user_path(@user)
    else
      flash[:danger] = "不正な時間入力がありました、再入力してください。"
      redirect_to edit_attendances_path(@user, params[:date])
    end
  end
  # 所属長承認申請お知らせモーダル
  def edit_superior_notice
    @user = User.find(params[:id])
    @users = User.application_manager_approval(superior: current_user)
    @attendance = Attendance.find_by(worked_on: params[:date], user_id: @user.id)
    @attendances = Attendance.where.not(worked_on: nil).where(superior_selector: @user.id)
  end
  
  def update_superior_notice
    @user = User.find(params[:id])
    @users = User.application_manager_approval(superior: current_user)
    @attendance = Attendance.find_by(worked_on: params[:date], user_id: @user.id)
    @attendances = Attendance.where.not(worked_on: nil).where(superior_selector: @user.id)
    if superior_notice_params.each do |id,item|
        if item["superior_change"] == "1"
         attendance = Attendance.find(id)
         attendance.update_attributes!(item)
        end
       end
      flash[:success] = "所属長承認申請についてを回答しました。"
      redirect_to user_path(@user)
    else
      flash[:danger] = "不正な時間入力がありました、再入力してください。"
      redirect_to edit_attendances_path(@user, params[:date])
    end
  end
  
  # 勤怠変更申請
  def edit
    @user = User.find(params[:id])
    @attendance = Attendance.find(params[:id])
    @first_day = first_day(params[:date])
    @last_day = @first_day.end_of_month
    @dates = user_attendances_month_date
  end

  def update
    @user = User.find(params[:id])
    @attendance = Attendance.find(params[:id])
    @first_day = first_day(params[:date])
    @last_day = @first_day.end_of_month
    @dates = user_attendances_month_date
    if attendances_invalid?
      attendances_params.each do |id,item|
        @attendance = Attendance.find(id)
        @attendance.update_attributes!(item)
        @attendance.update_attributes(attendance_mark: 2)
      end
      flash[:success] = "勤怠編集情報を更新しました。"
      redirect_to user_path(@user, params:{first_day: params[:date]})
    else
      flash[:danger] = "不正な入力がありました、再入力してください。"
      redirect_to edit_attendances_path(@user, params[:date])
    end
    rescue
      render :edit
  end
  
  # 勤怠変更申請お知らせモーダル
  def edit_attendance_notice
    @user = User.find(params[:id])
    @users = User.attendance_change(superior: current_user)
    @attendance = Attendance.find(params[:id])
    @attendances = Attendance.where.not(started_at_2: nil).where(superior_selection: @user.id)
  end
  
  def update_attendance_notice
    @user = User.find(params[:id])
    @users = User.attendance_change(superior: current_user)
    @attendance = Attendance.find(params[:id])
    @attendances = Attendance.where.not(started_at_2: nil).where(superior_selection: @user.id)
    if attendance_notice_params.each do |id,item|
        if item["attendance_change"] == "1"
          attendance = Attendance.find(id)
          attendance.update_attributes(item)
        end
       end
      flash[:success] = "勤怠変更申請についてを回答しました。"
      redirect_to user_path(@user)
    else
      flash[:danger] = "不正な時間入力がありました、再入力してください。"
      redirect_to edit_attendances_path(@user, params[:date])
    end
  end
  
  # 残業申請
  def edit_overtime
    @user = User.find(params[:id])
    @day = Date.parse(params[:date])
    @attendance = @user.attendances.find_by(worked_on: params[:date])
    @first_day = first_day(params[:date])
    @last_day = @first_day.end_of_month
    @dates = user_attendances_month_date
  end
  
  def update_overtime
    @user = User.find(params[:id])
    if overtime_notice_params.each do |id,item|
        attendance = Attendance.find(id)
        attendance.update_attributes!(item)
        attendance.update_attributes!(overtime_mark: 2)
       end
      flash[:success] = "残業申請情報を更新しました。"
      redirect_to user_path(@user)
    else
      flash[:danger] = "不正な時間入力がありました、再入力してください。"
      redirect_to edit_attendances_path(@user, params[:date])
    end
  end
  # 残業申請お知らせモーダル
  def edit_overtime_notice
    @user = User.find(params[:id])
    @users = User.overtime_applied_users(superior: current_user)
    @attendance = Attendance.find(params[:id])
    @attendances = Attendance.where.not(expected_end_time: nil).where(superior_select: @user.id)
  end
  
  def update_overtime_notice
    @user = User.find(params[:id])
    @users = User.overtime_applied_users(superior: current_user)
    @attendance = Attendance.find(params[:id])
    @attendances = Attendance.where.not(expected_end_time: nil).where(superior_select: @user.id)
    if overtime_notice_params.each do |id,item|
        if item["overtime_change"] == "1"
         attendance = Attendance.find(id)
         attendance.update_attributes!(item)
        end
       end
      flash[:success] = "残業申請についてを回答しました。"
      redirect_to user_path(@user)
    else
      flash[:danger] = "不正な時間入力がありました、再入力してください。"
      redirect_to edit_attendances_path(@user, params[:date])
    end
  end
  
  # 勤怠ログ
  def time_log
    @logs = Attendance.where(attendance_mark: 3, attendance_change: true).where(user_id: current_user.id)
                      .where(worked_on: Time.zone.now.beginning_of_month..Time.zone.now.end_of_month)
  end
  
  def ajax
    date = Date.new(params[:value_year].to_i, params[:value_month].to_i)
    @logs = Attendance.where(attendance_mark: 3, attendance_change: true).where(user_id: current_user.id)
                      .where(worked_on: date.beginning_of_month..date.end_of_month)
    logs = render_to_string(
        partial: 'table_time_log'
      )
     render json: {
            logs: logs,
            success: true # クライアント(js)側へsuccessを伝えるために付加
          }
  end
  
  private
    # 所属長承認申請
    def superior_notice_params
      params.permit(attendances: [:superior_mark, :superior_change])[:attendances]
    end
    # 勤怠変更申請
    def attendances_params
      params.permit(attendances: [:started_at_2, :finished_at_2, :attendance_next, :note, :superior_selection])[:attendances]
    end
    def attendance_notice_params
      params.permit(attendances: [:started_at, :finished_at, :started_at_2, :finished_at_2, :note, :attendance_mark, :attendance_change])[:attendances]
    end
    # 残業申請
    def overtime_notice_params
      params.permit(attendances: [:expected_end_time, :overtime_work, :superior_select, :next, :overtime_mark, :overtime_change])[:attendances]
    end
    
    def attendances_invalid?
      attendances = true
      attendances_params.each do |id,item|
        if item[:started_at_2].blank? && item[:finished_at_2].blank?
          next
        elsif item[:started_at_2].blank? || item[:finished_at_2].blank?
          attendances = false
          break
        elsif item[:attendance_next] == "1"
          item[:finished_at_2] = item[:finished_at_2]
          next
        elsif item[:started_at_2] > item[:finished_at_2]
          attendances = false
          break
        end
      end
      return attendances
    end
    
end

app/helpers/attendances_helper.rb
module AttendancesHelper
  
  def current_time
    Time.new(
      Time.now.year,
      Time.now.month,
      Time.now.day,
      Time.now.hour,
      Time.now.min,0
     )
  end
  
  def working_times_2(started_at_2, finished_at_2)
    format("%.2f", (((finished_at_2 - started_at_2) / 60) / 60.0))
  end
  
  def working_times_attendance(started_at_2, finished_at_2)
    format("%.2f", ((((finished_at_2 - started_at_2) / 60) / 60.0 ) + 24.0))
  end
  
  def working_times(started_at, finished_at)
    format("%.2f", (((finished_at - started_at) / 60) / 60.0))
  end
  
  def working_times_sum(seconds)
    format("%.2f", seconds / 60 / 60.0)
  end
  
  def first_day(date)
    !date.nil? ? Date.parse(date) : Date.current.beginning_of_month
  end
  
  def user_attendances_month_date
    @user.attendances.where('worked_on >= ? and worked_on <= ?', @first_day, @last_day).order('worked_on')
  end

end

app/views/attendances/_edit_attendance_notice.html.erb
<% provide(:class_text, '勤怠変更') %>
<% provide(:button_text, '更新') %>

<!--勤怠変更お知らせmodal-->
<%= form_with(model: @user, url: update_attendance_notice_path(@user), local: true, method: :patch) do |f| %>
  <div class="modal-dialog modal-lg modal-dialog-center">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <% @users.each do |user| %>
        <div class="modal-body">
          <div class="row">
            <h4 class="modal-title text-center"><%= "【#{user.name}からの勤怠変更申請】" %></h4>
            <table class="table-bordered table-condensed">
              <thead>
                <tr>
                  <th rowspan="3">日付</th>
                  <th rowspan="3">曜日</th>
                  <th colspan="4">変更前</th>
                  <th colspan="4">変更後</th>
                  <th rowspan="3">備考</th>
                  <th rowspan="3">指示者確認㊞</th>
                  <th rowspan="3">変更</th>
                  <th rowspan="3">勤怠を確認する</th>
                </tr>
                <tr>
                  <th colspan="2">出社</th>
                  <th colspan="2">退社</th>
                  <th colspan="2">出社</th>
                  <th colspan="2">退社</th>
                </tr>
                <tr>
                  <th>時</th>
                  <th>分</th>
                  <th>時</th>
                  <th>分</th>
                  <th>時</th>
                  <th>分</th>
                  <th>時</th>
                  <th>分</th>
                </tr>
              </thead>
              <tbody>
                <% @attendances.where(user_id: user.id).order(:worked_on).each do |attendance| %>
                  <% unless attendance.attendance_change == true && attendance.attendance_mark == 3 %>
                    <%= fields_for "attendances[]", attendance do |af| %>
                      <tr>
                        <td><%= l(attendance.worked_on, format: :short) %></td>
                        <td>
                          <% if attendance.worked_on.wday == 0 %>
                            <font color="red">日</font>
                          <% elsif attendance.worked_on.wday == 6 %>
                            <font color="blue">土</font>
                          <% else %>
                            <%= %w{日 月 火 水 木 金 土}[attendance.worked_on.wday] %>
                          <% end %>
                        </td>
                        <td><%= attendance.started_at.to_s(:hour) if attendance.started_at.present? %></td>
                        <td><%= attendance.started_at.to_s(:min) if attendance.started_at.present? %></td>
                        <td><%= attendance.finished_at.to_s(:hour) if attendance.finished_at.present? %></td>
                        <td><%= attendance.finished_at.to_s(:min) if attendance.finished_at.present? %></td>
                        <td><%= attendance.started_at_2.to_s(:hour) if attendance.started_at_2.present? %></td>
                        <td><%= attendance.started_at_2.to_s(:min) if attendance.started_at_2.present? %></td>
                        <td><%= attendance.finished_at_2.to_s(:hour) if attendance.finished_at_2.present? %></td>
                        <td><%= attendance.finished_at_2.to_s(:min) if attendance.finished_at_2.present? %></td>
                        <td><%= af.text_field :note, class: "form-control" %></td>
                        <td><%= af.select(:attendance_mark, {"なし" => 1, "申請中" => 2, "承認" => 3, "否認" => 4})%></td>
                        <td><%= af.check_box :attendance_change, class: "checkbox inline" %></td>
                        <td><%= link_to "確認", show_confirmation_user_path(user, first_day: params[:date]), class: "btn btn-primary" %></td>
                      </tr>
                    <% end %>
                  <% end %>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      <% end %>
      <div class="center btn-modal-update">
        <%= f.submit "承認結果を送信する", class: "btn btn-primary" %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
      </div>
    </div>
  </div>
<% end %>

app/views/attendances/_edit_overtime.html.erb
<% provide(:class_text, '残業申請') %>
<% provide(:button_text, '更新') %>

<!--残業申請modal-->
<%= form_with(model: @user, url: update_attendances_overtime_path(@user), local: true, method: :patch) do |f| %>
  <div class="modal-dialog modal-lg modal-dialog-center">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="row">
          <h4 class="modal-title text-center">【残業申請】</h4>
          <table class="table-bordered table-condensed table-striped">
            <thead>
              <tr>
                <th>日付</th>
                <th>曜日</th>
                <th>終了予定時間</th>
                <th>翌日</th>
                <th>業務処理内容</th>
                <th>指示者確認㊞</th>
              </tr>
            </thead>
            <tbody>
              <% @dates.each do |day| %>
                <%= fields_for "attendances[]", day do |af| %>
                  <tr>
                    <th><%= l(@attendance.worked_on, format: :short) %></th>
                    <th>
                      <% if @day.wday == 0 %>
                        <font color="red"><%= %w{日 月 火 水 木 金 土}[@day.wday] %></font>
                      <% elsif @day.wday == 6 %>
                        <font color="blue"><%= %w{日 月 火 水 木 金 土}[@day.wday] %></font>
                      <% else %>
                        <%= %w{日 月 火 水 木 金 土}[@day.wday] %>
                      <% end %>
                    </th>
                    <th><%= af.time_field :expected_end_time, class: "form-control" %></th>
                    <th><%= af.check_box :next, class: "checkbox inline" %></th>
                    <th><%= af.text_field :overtime_work, class: "form-control" %></th>
                    <th><%= af.collection_select :superior_select, User.where(superior: true).where.not(id: @user.id), :id,:name %></th>
                  </tr>
                <% end %>
                <% break %>
              <% end %>
            </tbody>
          </table>
          <div class="btn-modal-update">
            <%= f.submit "残業申請", class: "btn btn-primary" %>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
      </div>
    </div>
  </div>
<% end %>

app/views/attendances/_edit_overtime_notice.html.erb
<% provide(:class_text, '残業申請') %>
<% provide(:button_text, '更新') %>

<!--残業申請お知らせmodal-->
<%= form_with(model: @user, url: update_overtime_notice_path(@user), local: true, method: :patch) do |f| %>
  <div class="modal-dialog modal-lg modal-dialog-center">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <% @users.each do |user| %>
        <div class="modal-body">
          <div class="row">
            <h4 class="modal-title text-center"><%= "【#{user.name}からの残業申請】" %></h4>
            <table class="table-bordered table-condensed">
              <thead>
                <tr>
                  <th>日付</th>
                  <th>曜日</th>
                  <th>終了予定時間</th>
                  <th>指定勤務終了時間</th>
                  <th>時間外時間</th>
                  <th>業務処理内容</th>
                  <th>指示者確認㊞</th>
                  <th>変更</th>
                  <th>勤怠を確認する</th>
                </tr>
              </thead>
              <tbody>
                <% @attendances.where(user_id: user.id).order(:worked_on).each do |attendance| %>
                  <% unless attendance.overtime_change == true && attendance.overtime_mark == 3 %>
                    <%= fields_for "attendances[]", attendance do |af| %>
                      <tr>
                        <td><%= l(attendance.worked_on, format: :short) %></td>
                        <td>
                          <% if attendance.worked_on.wday == 0 %>
                            <font color="red">日</font>
                          <% elsif attendance.worked_on.wday == 6 %>
                            <font color="blue">土</font>
                          <% else %>
                            <%= %w{日 月 火 水 木 金 土}[attendance.worked_on.wday] %>
                          <% end %>
                        </td>
                        <td><%= l(attendance.expected_end_time, format: :time) if attendance.expected_end_time.present? %></td>
                        <td><%= format_basic_time(@user.designated_work_end_time) %></td>
                        <td>
                          <% if attendance.next == true %>
                            <%= format_over_time(attendance.expected_end_time).to_f - format_basic_time(@user.designated_work_end_time).to_f %>
                          <% elsif attendance.expected_end_time.present? %>
                            <%= format_basic_time(attendance.expected_end_time).to_f - format_basic_time(@user.designated_work_end_time).to_f %>
                          <% end %>
                        </td>
                        <td><%= attendance.overtime_work %></td>
                        <td><%= af.select(:overtime_mark, {"なし" => 1, "申請中" => 2, "承認" => 3, "否認" => 4})%></td>
                        <td><%= af.check_box :overtime_change, class: "checkbox inline" %></td>
                        <td><%= link_to "確認", show_confirmation_user_path(user, first_day: params[:date]), class: "btn btn-primary" %></td>
                      </tr>
                    <% end %>
                  <% end %>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      <% end %>
      <div class="center btn-modal-update">
        <%= f.submit "承認結果を送信する", class: "btn btn-primary" %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
      </div>
    </div>
  </div>
<% end %>

app/views/attendances/_edit_superior_notice.html.erb
<% provide(:class_text, '所属長承認') %>
<% provide(:button_text, '更新') %>

<!--所属長承認お知らせmodal-->
<%= form_with(model: @user, url: update_superior_notice_path(@user), local: true, method: :patch) do |f| %>
  <div class="modal-dialog modal-lg modal-dialog-center">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <% @users.each do |user| %>
        <div class="modal-body">
          <div class="row">
            <h4 class="modal-title text-center"><%= "【#{user.name}からの１か月分の申請勤怠】" %></h4>
            <table class="table-bordered table-condensed">
              <thead>
                <tr>
                  <th>月</th>
                  <th>指示者確認㊞</th>
                  <th>変更</th>
                  <th>勤怠を確認する</th>
                </tr>
              </thead>
              <tbody>
                <% @attendances.where(user_id: user.id).order(:worked_on).each do |attendance| %>
                  <% unless attendance.superior_change == true && attendance.superior_mark == 3 %>
                    <%= fields_for "attendances[]", attendance do |af| %>
                      <tr>
                        <td><%= l(attendance.worked_on, format: :middle) %></td>
                        <td><%= af.select(:superior_mark, {"なし" => 1, "申請中" => 2, "承認" => 3, "否認" => 4})%></td>
                        <td><%= af.check_box :superior_change, class: "checkbox inline" %></td>
                        <td><%= link_to "確認", show_confirmation_user_path(user, first_day: params[:date]), class: "btn btn-primary" %></td>
                      </tr>
                    <% end %>
                  <% end %>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      <% end %>
      <div class="center btn-modal-update">
        <%= f.submit "承認結果を送信する", class: "btn btn-primary" %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
      </div>
    </div>
  </div>
<% end %>

app/views/attendances/edit.html.erb
<% provide(:title, "勤怠編集") %>

<%= render partial: 'shared/error_messages', locals: { product: @attendance} %>
<div>
  <h1>勤怠編集画面</h1>
  <%= form_with(model: @user, url: update_attendances_path(params: {id: @user.id}), local: :true, method: :patch) do |f| %>
    <table class="table-bordered table-striped table-condensed">
      <thead>
        <tr>
          <th>日付</th>
          <th>曜日</th>
          <th>出社</th>
          <th>退社</th>
          <th>翌日</th>
          <th>在社時間</th>
          <th>備考</th>
          <th>指示者確認</th>
        </tr>
      </thead>
      <tbody>
        <% @dates.each do |day| %>
          <%= fields_for "attendances[]", day do |af| %>
            <tr>
              <td><%= day.worked_on.to_s(:date) %></td>
              <td>
                <% if day.worked_on.wday == 0 %>
                  <font color="red"><%= %w{日 月 火 水 木 金 土}[day.worked_on.wday] %></font>
                <% elsif day.worked_on.wday == 6 %>
                  <font color="blue"><%= %w{日 月 火 水 木 金 土}[day.worked_on.wday] %></font>
                <% else %>
                  <%= %w{日 月 火 水 木 金 土}[day.worked_on.wday] %>
                <% end %>
              </td>
              <td>
                <% if day.worked_on > Date.today %>
                  <%= af.time_field :started_at_2, :readonly => true, class: "form-control" %>
                <% elsif day.started_at.present? %>
                  <%= af.time_field :started_at_2, value: (day.started_at.strftime("%H:%M")), class: "form-control" %>
                <% else %>
                  <%= af.time_field :started_at_2, class: "form-control" %>
                <% end %>
              </td>
              <td>
                <% if day.worked_on > Date.today %>
                  <%= af.time_field :finished_at_2, :readonly => true, class: "form-control" %>
                <% elsif day.finished_at.present? %>
                  <%= af.time_field :finished_at_2, value: (day.finished_at.strftime("%H:%M")), class: "form-control" %>
                <% else %>  
                  <%= af.time_field :finished_at_2, class: "form-control" %>
                <% end %>
              </td>
              <td>
                <% if day.worked_on > Date.today %>
                  <%= af.check_box :attendance_next, :disabled => true, class: "checkbox inline" %>
                <% else %>  
                  <%= af.check_box :attendance_next, class: "checkbox inline" %>
                <% end %>
              </td>
              <td>
                <% if day.started_at_2.present? && day.finished_at_2.present? && day.attendance_next == true %>
                  <%= working_times_attendance(day.started_at_2, day.finished_at_2) %>
                <% elsif day.started_at_2.present? && day.finished_at_2.present? %>
                  <%= working_times_2(day.started_at_2, day.finished_at_2) %>
                <% elsif day.started_at.present? && day.finished_at.present? %>
                  <%= working_times(day.started_at, day.finished_at) %>
                <% end %>
              </td>
              <td>
                <% if day.worked_on > Date.today %>
                  <%= af.text_field :note, :readonly => true, class: "form-control" %>
                <% else %>  
                  <%= af.text_field :note, class: "form-control" %>
                <% end %>
              </td>
              <td>
                <% if day.worked_on > Date.today %>
                  <%= af.collection_select :superior_selection, User.where(superior: true).where.not(id: @user.id), :id,:name, {}, disabled: true, style: "display: none;" %>
                <% else %>
                  <%= af.collection_select :superior_selection, User.where(superior: true).where.not(id: @user.id), :id,:name, :include_blank => true, selected: params[:id] %>
                <% end %>
              </td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
    <div class="btn-attendances-update">
      <%= f.submit "勤怠変更申請", class: "btn btn-primary" %>
      <%= link_to "キャンセル", user_path(@user, params:{first_day: @first_day }), class: "btn btn-default btn-block" %>
    </div>
  <% end %>
</div>

app/views/attendances/edit_attendance_notice.js.erb
$("#edit-attendance-notice").html("<%= escape_javascript(render 'edit_attendance_notice') %>");
$("#edit-attendance-notice").modal("show");