config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get '/signup',   to: 'users#new'
  get '/login',    to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  # 拠点情報
  resources :bases
  # 出勤中社員
  get '/workers', to: 'attendances#index'
  # 基本情報更新 未使用
  get '/edit_basic_info/:id', to: 'users#edit_basic_info', as: :basic_info
  patch 'update_basic_info', to: 'users#update_basic_info'
  # 勤怠編集更新
  get 'users/:id/attendances/:date/edit', to: 'attendances#edit', as: :edit_attendances
  patch 'users/:id/attendances/:date/update', to: 'attendances#update', as: :update_attendances
  # 残業申請更新
  get 'users/:id/attendances/:date/edit_overtime', to: 'attendances#edit_overtime', as: :edit_attendances_overtime
  patch 'users/:id/attendances/:date/update_overtime', to: 'attendances#update_overtime', as: :update_attendances_overtime
  # 各種お知らせ
  get 'users/:id/attendances/:date/edit_superior_notice', to: 'attendances#edit_superior_notice', as: :edit_superior_notice
  patch 'users/:id/attendances/:date/update_superior_notice', to: 'attendances#update_superior_notice', as: :update_superior_notice
  get 'users/:id/attendances/:date/edit_attendance_notice', to: 'attendances#edit_attendance_notice', as: :edit_attendance_notice
  patch 'users/:id/attendances/:date/update_attendance_notice', to: 'attendances#update_attendance_notice', as: :update_attendance_notice
  get 'users/:id/attendances/:date/edit_overtime_notice', to: 'attendances#edit_overtime_notice', as: :edit_overtime_notice
  patch 'users/:id/attendances/:date/update_overtime_notice', to: 'attendances#update_overtime_notice', as: :update_overtime_notice
  # １ヶ月分の勤怠申請
  patch 'users/:id/attendances/:date/update_one_month', to: 'attendances#update_one_month', as: :update_one_month
  # 勤怠ログ
  get 'users/:id/attendances/:date/time_log', to: 'attendances#time_log', as: :time_log
  get 'ajax', to: 'attendances#ajax', as: :ajax
  
  resources :users do
    get :show_confirmation, on: :member
    collection { post :import }
    resources :attendances, only: :create
  end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "勤怠管理システム", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "トップへ", root_path %></li>
        <% if logged_in? %>
          <li>
            <% if current_user.admin? %>
              <%= link_to "ユーザー一覧", users_path %>
            <% end %>
          </li>
          <li>
            <% if current_user.admin? %>
              <%= link_to "出勤社員一覧", workers_path %>
            <% end %>
          </li>
          <li>
            <% if current_user.admin? %>
              <%= link_to "拠点情報の修正", bases_path %>
            <% end %>
          </li>
          <li>
            <% if current_user.admin? %>
              <%= link_to "基本情報の修正", basic_info_path(current_user{:admin}) %>
            <% end %>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              アカウント<b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li>
                <% unless current_user.admin %>
                  <%= link_to "ユーザー勤怠情報表示", current_user %>
                <% end %>
              </li>
              <li><%= link_to "アカウント情報", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "ログアウト", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "ログイン", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 
                               'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %> <!-- HTML simがこの１行で済む -->                           
  </head>

  <body>
    <%= render 'layouts/header' %> <!-- headerの内容がこの１行で収まる-->
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>